### PR TITLE
Rep adapter

### PR DESCRIPTION
**Pull request by Winterhart**
# Description
Common Shared Interface for our replicas.

# How Has This Been Tested?
Not at all :P

see our chain of emails

### CODE REVIEW

**Comment by g-harel** [comment]
How do we send back log messages? A few of us had made all the methods return string for that case

**Comment by Winterhart** [comment]
This is an interface for our CORBA Replica, the idea is to convert our `string` message saying success to a BOOLEAN to make all message uniform

**Comment by prince-chrismc** [comment]
can we close this since it's inactive?

**Comment by prince-chrismc** [comment]
inactive

**Pull request closed without merging**
